[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyczan"
version = "0.0.0"
description = "C++ high-performance Python acceleration toolkit"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "zan", email = "13667605889@139.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[tool.setuptools.packages.find]
where = ["src/py"]