from typing import Any, Dict as DictType, List

class Dict:
    def __init__(self) -> None: ...
    def OpenOrCreate(self, name: str, total_size: int = ...) -> bool: ...
    def Close(self) -> None: ...

    def Set(self, key: str, value: Any) -> None: ...
    def Get(self, key: str) -> Any: ...
    def Delete(self, key: str) -> bool: ...
    def Has(self, key: str) -> bool: ...
    def Size(self) -> int: ...
    def Clear(self) -> None: ...
    def Keys(self) -> List[str]: ...

    def Increment(self, key: str) -> int: ...
    def Decrement(self, key: str) -> int: ...
    def Add(self, key: str, value: float) -> float: ...

    def Alloc(self, bytes: int) -> memoryview: ...
    def Free(self, buf: memoryview) -> None: ...

    def Status(self) -> DictType[str, Any]: ...

    def IsOpen(self) -> bool: ...
    def Name(self) -> str: ...

    @staticmethod
    def Reset(name: str) -> None: ...

    # dict protocol
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...

    def __enter__(self) -> "Dict": ...
    def __exit__(self, *args: Any) -> None: ...
